### ISSUE TITLE
git checkout failed wegen Komma-Datei

### ISSUE THREAD

**Issue by fabianlupa** [1DSAG/ABAP-Leitfaden#15]
Hi, die Komma-Datei unter `ADT-Leitfaden/,.` macht zumindest unter Windows Probleme. Sollte das eine sein um in git einen eigentlich leeren Ordner zu führen, kenne ich das über .gitkeep Dateien.

![image](https://github.com/user-attachments/assets/0fbe4526-cb4e-4333-b42c-369a9234e787)

![image](https://github.com/user-attachments/assets/1bbb98f7-dcc1-4450-be9b-a0059e0a4a6d)

Die README hat Anleitungen für den GitHub Web Editor und lokal mit Docker, was wohl beides das Problem ausschließt, aber finde ich trotzdem unnötig einschränkend und würde empfehlen die `,.` Datei durch eine `.gitkeep` Datei zu ersetzen, wenn die überhaupt benötigt wird (der Ordnername ist ja auch noch nicht angepasst).

Ping @Xexer

**Comment by Xexer** [comment]
Hallo Fabian,
hatte die beiden Repos mal miteinander verglichen und der Ordner existiert dort nicht, ist wahrscheinlich ausversehen rein gekommmen. Habe das Repository aufgeräumt und sollte damit nun wieder bei dir funktionieren.

Grüße
Björn

**Comment by fabianlupa** [comment]
Klappt, danke!
