### ISSUE TITLE
Branch protection für main

### ISSUE THREAD

**Issue by fabianlupa** [1DSAG/ABAP-Leitfaden#45]
Kann mich irren, sieht aber gerade so aus, als wäre main ungeschützt und ein git-Neuling könnte irrtümlich per google-foo ein `push -f` darauf machen.

![image](https://github.com/user-attachments/assets/abeafb42-8781-4757-a7ff-4b2b4e81580d)

**Comment by fabianlupa** [comment]
@Xexer Auf Basis einiger PRs könnte das bald passieren :D Kannst du main protecten oder mir Rechte geben, das einzurichten? Scheint tatsächlich aktuell aus, ca0f02398408904006709117c4361486b576a5f2 kam ohne PR in main.

**Comment by Xexer** [comment]
Habe dir Berechtigungen gegeben.
